export const COMPANIES = [
    "EnduroSat",
    "DHL",
    "TINQIN",
    "Strypes",
    "MAN",
    "myPOS",
    "Degiro",
    "Evrotrust",
    "AiOpsGroup",
    "GeoWealth",
    "Scaleflex",
    "Tide",
    "GemSeek",
    "UltraPlay",
    "GAN",
    "Betty",
    "Merkle",
    "Candor",
    "Codiit",
    "OSF",
    "Despark",
    "MM Solutions",
    "Epsilon Telecom",
]
